name: poultry_farm
description: A professional poultry farm management application with SMS notifications and Firebase integration.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.1

  # UI Components
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  intl: ^0.18.1
  
  # SMS Functionality - Using platform channels
  # sms_advanced: ^1.0.1 - Removed due to AGP compatibility
  permission_handler: ^11.0.1
  url_launcher: ^6.2.4
  
  # Export/Backup
  excel: ^4.0.2
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  pdf: ^3.10.7
  
  # State Management
  provider: ^6.1.1
  
  # Utilities
  uuid: ^4.2.2
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/
  #   - icons/
